export const ACCESS_TOKEN = 'Access-Token'
export const PLAN_DATA = 'PLAN_DATA'
export const LOCATION_DATA = 'LOCATION_DATA'
export const PROJECT_DATA = 'PROJECT_DATA'
export const SEL_PROJECT = 'SEL_PROJECT'
